# tomcat启动配置
servlet:
  context-path: /demo
  port: 8888

# profiles配置
spring:
  profiles:
    active: dev

  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true&failOverReadOnly=false
    username: root
    password: pheonix

  # Bean生成Table
  jpa:
    hibernate:
      ddl-auto: update  # 第一次建表create，后面用update
    show-sql: true

  # Mongo配置
  data:
    mongodb:
      uri: mongodb://localhost:27017/test

  redis:
    host: localhost
    port: 6379
    #password:
    database: 1
    #timeout: 0
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 500
      min-idle: 0

# Mybatis的xml管理
mybatis:
  mapper-locations: classpath*:mybatis/*Mapper.xml
  type-aliases-package: com.example.demo.entity

# 输出日志
logging:
  level:
    com: # Mybatis显示sql
      example:
        demo:
          mapper: debug

    org: #Mongo显示日志
      springframework:
        data:
          mongodb:
            core: DEBUG
